apiVersion: v2
name: openmetadata
maintainers:
  - name: RezaB
    email: r.beygi1@gmail.com
appVersion: "1.1.7"
version: "1.1.7"
kubeVersion: ">=1.20.0"
description: "OpenMetaData 1.1.7" 
type: application

dependencies:
  - name: mysql
    version: "8.0.32"
    alias: mysql
    condition: mysql.enabled
  - name: elasticsearch
    version: "7.16.3"
    condition: elasticsearch.enabled
  - name: airflow
    version: "8.8.0"
    condition: airflow.enabled
  - name: omd
    version: "1.1.7"