apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
data:
  openmetadata-mysql-password: b3Blbm1ldGFkYXRhX3Bhc3N3b3Jk
type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
data:
  openmetadata-airflow-password: YWRtaW4=
type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  name: airflow-mysql-secrets
data:
  airflow-mysql-password: YWlyZmxvd19wYXNz
type: Opaque
